name: Update mirror

on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
env:
  MIRROR: ""
  
jobs:
  update:
    name: Update MIRROR
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run python script
        run: |
          set -e
          python -m pip install requests
          python main.py ${{ secrets.SENDER_EMAIL }} "${{ secrets.SENDER_PASSWORD }}"
          # echo "Mirror -> $MIRROR"
         # echo "MIRROR=$MIRROR" >> $GITHUB_ENV
      
      - name: Update mirror if it differs
        run: |
          set -e
          MIRROR_FILE="mirror.txt"
          MIRROR=${{ env.MIRROR }}
          if [[ ! -e $MIRROR_FILE ]] || [[ "$(cat $MIRROR_FILE)" != "$MIRROR" ]]; then
            echo -n "$MIRROR" > $MIRROR_FILE
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add $MIRROR_FILE
            git commit -m "Updating mirror"
            git push
          fi
